#!/usr/bin/env python3
"""
Pull data from Airtable into Postgres tables created by airtable_schema_to_postgres.

Uses airtable_id to upsert base rows and to resolve Airtable link fields to our UUIDs,
then fills junction tables with (left_id, right_id). Requires the schema to already
exist (run the schema script with --apply or apply the migration first).

Prerequisites:
  - .env with AIRTABLE_API_KEY, AIRTABLE_BASE_ID, and DATABASE_URL (Postgres)
  - Tables already created (same shape as generated by airtable_schema_to_postgres)
  - psycopg2: uv sync --extra ddl

Usage (from project root):
  uv run python scripts/airtable_pull_data.py --all-tables
  uv run python scripts/airtable_pull_data.py --tables "Schools" "Workshops"
  uv run python scripts/airtable_pull_data.py --all-tables --dry-run
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Project root
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

try:
    import psycopg2
except ImportError:
    psycopg2 = None  # type: ignore[assignment]

from scripts.airtable_schema_to_postgres import (
    Api,
    build_junction_tables,
    creation_order,
    fetch_all_records,
    get_all_table_names,
    infer_schema,
)
from scripts.airtable_schema_to_postgres import InferredTable as InferredTableType
from scripts.airtable_schema_to_postgres import JunctionTable as JunctionTableType


def _quote_ident(name: str) -> str:
    return f'"{name}"'


def _convert_value(val: Any, pg_type: str) -> Any:
    """Convert Airtable value to a value suitable for Postgres (for INSERT)."""
    if val is None or (isinstance(val, str) and val.strip() == ""):
        return None
    if pg_type == "BOOLEAN":
        return bool(val) if val is not None else None
    if pg_type == "BIGINT":
        try:
            return int(val) if val is not None else None
        except (TypeError, ValueError):
            return None
    if pg_type == "DOUBLE PRECISION":
        try:
            return float(val) if val is not None else None
        except (TypeError, ValueError):
            return None
    if pg_type == "TIMESTAMPTZ":
        # Only pass values that look like ISO timestamps; URLs or other strings become NULL
        if not isinstance(val, str):
            return None
        s = val.strip()
        if s.startswith("http://") or s.startswith("https://"):
            return None
        if len(s) >= 19 and s[0].isdigit() and "T" in s and ("Z" in s or "+" in s or (len(s) >= 6 and s[-6] in "-+" and s[-3] == ":")):
            return val
        if len(s) >= 19 and s[0].isdigit() and s.count("T") == 1 and s.count("-") >= 2 and s.count(":") >= 2:
            return val
        if hasattr(val, "isoformat"):
            return val.isoformat()
        return None
    if pg_type == "JSONB":
        if isinstance(val, (dict, list)):
            return json.dumps(val)
        return str(val) if val is not None else None
    return str(val) if val is not None else None


def _record_to_row(
    rec: dict[str, Any],
    t: InferredTableType,
) -> dict[str, Any]:
    """Build a row dict for INSERT: airtable_id, created_time, and non-linked columns."""
    row: dict[str, Any] = {
        "airtable_id": rec["id"],
        "created_time": rec.get("createdTime"),
    }
    fields = rec.get("fields", {})
    for col in t.columns:
        if col.is_linked_record:
            continue
        raw = fields.get(col.airtable_field_name) if col.airtable_field_name else None
        row[_quote_ident(col.snake_name)] = _convert_value(raw, col.pg_type)
    return row


def _upsert_base_table(
    cur: Any,
    table_snake: str,
    t: InferredTableType,
    schema: str,
) -> tuple[dict[str, str], list[dict[str, Any]]]:
    """
    Upsert all records. Returns (airtable_id -> id map, list of full rows including id).
    """
    id_map: dict[str, str] = {}
    rows_with_id: list[dict[str, Any]] = []
    if not t.records:
        return id_map, rows_with_id

    existing = _get_table_columns(cur, schema, table_snake)
    if "airtable_id" not in existing:
        raise RuntimeError(f'Table "{schema}"."{table_snake}" has no column airtable_id. Create the schema first (airtable_schema_to_postgres.py -o migration.sql then supabase db reset).')

    cols = ["airtable_id"]
    if "created_time" in existing:
        cols.append("created_time")
    for col in t.columns:
        if not col.is_linked_record and col.snake_name in existing:
            cols.append(_quote_ident(col.snake_name))

    schema_q = _quote_ident(schema)
    table_q = _quote_ident(table_snake)
    columns_sql = ", ".join(cols)
    placeholders = ", ".join(["%s"] * len(cols))
    update_set = ", ".join(
        f"{c} = EXCLUDED.{c}" for c in cols if c != "airtable_id"
    )
    sql = f"""
        INSERT INTO {schema_q}.{table_q} ({columns_sql})
        VALUES ({placeholders})
        ON CONFLICT (airtable_id) DO UPDATE SET {update_set}
        RETURNING id, airtable_id
    """
    for rec in t.records:
        row = _record_to_row(rec, t)
        values = []
        for c in cols:
            if c == "airtable_id":
                values.append(row["airtable_id"])
            elif c == "created_time":
                values.append(row.get("created_time"))
            else:
                values.append(row.get(c))
        cur.execute(sql, values)
        for r in cur.fetchall():
            id_map[r[1]] = str(r[0])
    return id_map


def _get_linked_record_ids(rec: dict[str, Any], airtable_field_name: str | None) -> list[str]:
    """Get list of Airtable record IDs from a linked-record field."""
    if not airtable_field_name:
        return []
    val = rec.get("fields", {}).get(airtable_field_name)
    if not isinstance(val, list):
        return []
    return [x for x in val if isinstance(x, str) and x.startswith("rec")]


def _get_table_columns(cur, schema, table_snake):
    cur.execute("SELECT column_name FROM information_schema.columns WHERE table_schema = %s AND table_name = %s", (schema, table_snake))
    return {r[0] for r in cur.fetchall()}


def _sync_junction(
    cur: Any,
    j: JunctionTableType,
    inferred: dict[str, InferredTableType],
    id_maps: dict[str, dict[str, str]],
    schema: str,
) -> int:
    """Insert junction rows. Returns count inserted. Skips links whose target is missing."""
    left_table = inferred.get(j.left_table_snake)
    right_table = inferred.get(j.right_table_snake)
    if not left_table or not right_table:
        return 0
    col = None
    for c in left_table.columns:
        if c.is_linked_record and c.snake_name == j.field_snake and c.airtable_field_name:
            col = c
            break
    if not col:
        return 0

    left_map = id_maps.get(j.left_table_snake, {})
    right_map = id_maps.get(j.right_table_snake, {})
    schema_q = _quote_ident(schema)
    table_q = _quote_ident(j.table_snake)
    left_col = _quote_ident(f"{j.left_table_snake}_id")
    right_col = _quote_ident(f"{j.right_table_snake}_id")

    insert_sql = f"""
        INSERT INTO {schema_q}.{table_q} ({left_col}, {right_col})
        VALUES (%s, %s)
        ON CONFLICT ({left_col}, {right_col}) DO NOTHING
    """
    count = 0
    for rec in left_table.records:
        left_airtable_id = rec["id"]
        left_id = left_map.get(left_airtable_id)
        if not left_id:
            continue
        for rec_id in _get_linked_record_ids(rec, col.airtable_field_name):
            right_id = right_map.get(rec_id)
            if not right_id:
                continue
            try:
                cur.execute(insert_sql, (left_id, right_id))
                if cur.rowcount:
                    count += 1
            except Exception:
                pass
    return count


def run_pull(
    table_names: list[str] | None,
    api_key: str,
    base_id: str,
    database_url: str,
    schema: str = "public",
    all_tables: bool = False,
    dry_run: bool = False,
) -> dict[str, int]:
    """
    Fetch Airtable data and upsert into Postgres. Returns counts per table/junction.
    """
    if Api is None:
        raise RuntimeError("pyairtable is required")
    if psycopg2 is None:
        raise RuntimeError("psycopg2 is required. Install with: uv sync --extra ddl")

    api = Api(api_key)
    base = api.base(base_id)

    if all_tables:
        table_names = get_all_table_names(api, base_id)
        if not table_names:
            raise RuntimeError("Base has no tables")
    if not table_names:
        raise ValueError("No tables. Use --tables or --all-tables.")

    records_by_table = fetch_all_records(api, base_id, table_names)
    base_schema = base.schema()
    inferred, _ = infer_schema(table_names, records_by_table, base_schema=base_schema)
    junctions = build_junction_tables(inferred)
    order = creation_order(inferred, junctions)

    counts: dict[str, int] = {}
    if dry_run:
        for table_snake in order:
            if table_snake in inferred:
                counts[table_snake] = len(inferred[table_snake].records)
            else:
                counts[table_snake] = 0
        return counts

    conn = psycopg2.connect(database_url)
    id_maps: dict[str, dict[str, str]] = {}
    try:
        with conn.cursor() as cur:
            for table_snake in order:
                if table_snake in inferred:
                    t = inferred[table_snake]
                    id_maps[table_snake] = _upsert_base_table(cur, table_snake, t, schema)
                    counts[table_snake] = len(id_maps[table_snake])
                else:
                    j = next((x for x in junctions if x.table_snake == table_snake), None)
                    if j:
                        n = _sync_junction(cur, j, inferred, id_maps, schema)
                        counts[table_snake] = n
        conn.commit()
    finally:
        conn.close()

    return counts


def main() -> int:
    parser = argparse.ArgumentParser(description="Pull Airtable data into Postgres")
    parser.add_argument("--tables", nargs="*", default=None, help="Table names (omit with --all-tables)")
    parser.add_argument("--all-tables", action="store_true", help="Pull all tables in the base")
    parser.add_argument("--schema", default="public", help="Postgres schema")
    parser.add_argument("--dry-run", action="store_true", help="Only fetch and report row counts, do not write")
    args = parser.parse_args()

    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from src.config import settings

    if not settings.airtable_api_key or not settings.airtable_base_id:
        print("Error: AIRTABLE_API_KEY and AIRTABLE_BASE_ID must be set in .env", file=sys.stderr)
        return 1
    if not args.dry_run and not settings.database_url:
        print("Error: DATABASE_URL must be set in .env (or use --dry-run)", file=sys.stderr)
        return 1

    try:
        counts = run_pull(
            args.tables if not args.all_tables else None,
            settings.airtable_api_key,
            settings.airtable_base_id,
            settings.database_url or "",
            schema=args.schema,
            all_tables=args.all_tables,
            dry_run=args.dry_run,
        )
        for name, n in sorted(counts.items()):
            print(f"{name}: {n}")
        return 0
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        raise


if __name__ == "__main__":
    sys.exit(main())
